---
title: 'MCSR Handbook'
date: "Last updated on `r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    toc: true
    theme: yeti
    highlight: haddock
    pandoc_args: [ 
      "--output=index.html" 
    ]
---

This is a reference guide for the [MCSR](http://mcsr.olemiss.edu/).

## What is the MCSR?

The Mississippi Center for Supercomputing Research (MCSR) provides computing resources, training, and support for faculty, staff, and students at all of Mississippi’s public Institutions of Higher Learning (IHLs).

The MCSR was established by the Mississippi legislature in 1987, and given the mission to provide high-performance computing support to all the campuses governed by the Board of Trustees of State Institutions of Higher Learning. Funded by the legislature each of the last 19 years, the center has attracted researchers into the state of Mississippi, enabled Mississippi researchers to conduct research on a much higher plane, and helped them to garner research money for graduate students and equipment. Today, MCSR continues to enhance both the instructional and research climates for all IHL institutions.

MCSR enables researchers to conduct research on a much higher plane; makes it possible for Mississippi researchers to gain priority on computer time in order to meet grant deadlines; and empowers Mississippi universities to garner research money which funds graduate students and equipment. 

MCSR Management maintains a list of active grant-funded research projects for performance reporting purposes. The list is updated semi-annually; researchers are encouraged to watch for an email requesting information on new grants each December and June. If you have new grants and would like to report these as soon as they become active, please send email to assist@mcsr.olemiss.edu. 

### What is a supercomputer?

A supercomputer is a computer with a high level of performance compared to a general-purpose computer. Performance of a supercomputer is measured in floating-point operations per second (FLOPS) instead of million instructions per second (MIPS).

### How many supercomputers does the MCSR have?

The MCSR currently has three supercomputers: `Sequoia`, `Catalpa`, and `Maple`.

`Sequoia` is a cluster and MCSR’s oldest supercomputer. It consists of 124 nodes with a total of 1304 CPU cores interconnected with a mixture of DDR and QDR Infiniband. Nodes have up to 35GB of memory and a varying number of CPU cores. It has the most software installed, and is a good system to start with if you don’t need a lot of memory.

`Catalpa` is MCSR’s only single-image, shared memory system, and should only be used for large memory jobs that are unable to be run across multiple nodes on one of the clusters. It is an SGI UV 2000 with 320 processor cores and 2.5 terabytes of shared memory.

`Maple` is a Cray cluster with a theoretical peak performance of 70 TFLOPS, 47 compute nodes, a total of 1228 CPU cores, 29 NVIDIA Kepler K20 GPUs, and 3.3TB of memory. It is the future workhorse cluster of MCSR, but does not yet have the installed software base of Sequoia and Catalpa. This cluster is grant funded in part by the National Science Foundation (CHE-1338056).  

  
## How do I get an account?

Submit this [form](http://cypress.mcsr.olemiss.edu/resdb2/user_info.html). Register with a university or school email address. After you submit the form, you will receive an email confirming your submission and soon after confirming the creation of your account with password information.

Accounts that remain inactive for six months will be automatically restricted, which will prevent you from logging in. Restricted accounts will be preserved for a few months, and if unclaimed, may be then be deleted from the system. 


## How much storage space will I have?

Each user is guaranteed 600GB of storage space. There is a hard cap of 800 GB. It is your responsibility to backup all important files in your accounts and keep your disk usage to a reasonable minimum. You may use the `quota` command to find out how much storage space you have available and are using.

## How do I contact the MCSR?

The best way to contact the MCSR is by sending an email to [assist@mcsr.olemiss.edu](mailto:assist@mcsr.olemiss.edu).


## Connecting to the MCSR supercomputers

Users connect to MCSR supercomputers via the Secure Shell (SSH) protocol.

We recommend [MobaXterm](https://mobaxterm.mobatek.net/download.html) for *Windows* users. It is an approved UMMC software.

*Mac OS X* and *Linux* users should use the command line SSH client, named ssh, that is included with their operating system.

The MCSR has a gateway, hpcwoods, that must first be connected to in order to access the [supercomputers](http://mcsr.olemiss.edu/supercomputers/) (Sequioa, Catalpa, Maple). 

### Login to hpcwoods

```bash
ssh -v -X username@hpcwoods.olemiss.edu
```
`-v` = Verbose mode
`-X` = Enables X11 forwarding

View more ssh commands at https://www.ssh.com/ssh/command/.

When prompted for a password, use the password that was emailed to you. You will be asked to create a new password upon logging in.

After your login/password change is successful, you can login to one of the supercomputers (Maple, Sequoia, or Catalpa).

### Login to Maple, Sequoia, or Catalpa

```bash
ssh -v -X username@sequoia.mcsr.olemiss.edu
```
Replace `sequioa` in the line above with `maple` or `catalpa` to login to those supercomputers.

To logout of a server, type `exit`.


## Using the MCSR for Computational Projects


### Running Jobs

### PBS Job Examples